# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Contours2SurfacePlugin
                                 A QGIS plugin
 Generate 3D fault surfaces or geological meshes from top, middle, and bottom contour lines in QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-05
        copyright            : (C) 2025 by CRESCENT
        email                : lbachelo@uoregon.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# ---- NEW: ensure vendored ccfm is importable before anything else ----
import sys
from pathlib import Path

_vendored_repo = Path(__file__).parent / "vendor" / "ccfm"
if _vendored_repo.is_dir():
    # Put the repo root on sys.path so `import ccfm` finds ccfm/*.py inside it
    sys.path.insert(0, str(_vendored_repo))

try:
    import ccfm  # noqa: F401
except Exception as e:
    # Helpful error if dev forgot to init submodules or packaging missed the folder
    raise ImportError(
        "ccfm not found. If you are developing locally, run:\n"
        "    git submodule update --init --recursive\n"
        "If you installed from a ZIP, please rebuild ensuring vendor/ccfm/** is included."
    ) from e
# ----------------------------------------------------------------------

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Contours2SurfacePlugin class from file Contours2SurfacePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .contours2surface import Contours2SurfacePlugin
    return Contours2SurfacePlugin(iface)