# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Contours2SurfacePlugin
                                 A QGIS plugin
 Generate 3D fault surfaces or geological meshes from top, middle, and bottom contour lines in QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by CRESCENT
        email                : lbachelo@uoregon.edu
***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify *
 *   it under the terms of the GNU General Public License as published by *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QFileDialog, QInputDialog
from qgis.core import QgsProject, QgsVectorLayer, QgsWkbTypes


def _feature_geometry_has_z(feature):
    geom = feature.geometry()
    if geom is None or geom.isEmpty():
        return False
    return QgsWkbTypes.hasZ(geom.wkbType())
import os, tempfile, json

from ccfm.ccfm import make_tri_mesh, write_cfm_tri_meshes
from ccfm.mesh_helpers import prepare_fault_contours, make_mesh_from_prepared_contours, get_invalid_contour_messages, \
    estimate_triangle_count
from .input_dialog import MeshInputDialog
from itertools import islice


def _qvariant_to_float(qvar, return_none=False):
    try:
        val = float(qvar)
    except:

        if qvar is None or isinstance(qvar, QVariant) and qvar.isNull():
            val = None

        elif isinstance(qvar, QVariant) and hasattr(qvar, "value"):
            val = float(qvar.value())

        elif isinstance(qvar, QVariant):
            val = qvar.toDouble()[0]

        else:
            if return_none:
                val = None
            else:
                raise ValueError(f"Cannot turn {qvar} to float")
    return val


class Contours2SurfacePlugin:
    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', f'Contours2SurfacePlugin_{locale}.qm')
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
        self.actions = []
        self.menu = self.tr('&Contours2Surface')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('Contours2SurfacePlugin', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True,
                   add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, "icon.png")
        self.add_action(
            icon_path,
            text=self.tr('Generate 3D Surface from Contours'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        # Check if there's a suitable layer already selected/active
        preselected_layer = None

        # Try getting the active layer first
        active_layer = self.iface.activeLayer()
        if active_layer:
            from .input_dialog import is_valid_linestring_layer
            if is_valid_linestring_layer(active_layer):
                preselected_layer = active_layer

        # If no active layer, try selected layers
        if not preselected_layer:
            selected_layers = self.iface.layerTreeView().selectedLayers()
            if len(selected_layers) == 1:
                from .input_dialog import is_valid_linestring_layer
                layer = selected_layers[0]
                if is_valid_linestring_layer(layer):
                    preselected_layer = layer

        # Always open the dialog, but with preselected layer if available
        dlg = MeshInputDialog(None, preselected_layer=preselected_layer)

        # Connect to the process signal
        dlg.process_requested.connect(lambda: self.process_contours(dlg))

        # Show dialog and keep it open until user closes it
        dlg.exec_()

    def process_contours(self, dlg):
        """Process the contours based on dialog settings"""
        # Get the selected layer and contours from the dialog
        layer = dlg.get_selected_layer()
        contours = dlg.get_selected_contours()

        crs = layer.crs()

        # ---------- 1) If CRS is defined: require geographic ----------
        print("checking projection")
        if crs.isValid():
            print(crs)
            if not crs.isGeographic():
                QMessageBox.critical(
                    None,
                    "Invalid CRS",
                    (
                        "The contour layer uses a projected CRS.\n\n"
                        f"Current layer CRS:\n{crs.authid() or 'unknown'} - {crs.description()}\n\n"
                        "The meshing tools expect longitude/latitude coordinates in a "
                        "geographic CRS such as EPSG:4326.\n"
                        "Please reproject your contours to EPSG:4326 in QGIS and try again."
                    ),
                )
                return
            else:
                print("valid projection")
        else:
            # ---------- 2) If CRS is NOT defined: inspect coordinates ----------
            def coords_look_lonlat(contour_wrappers, max_features=20, max_points=200):
                """
                Check if coordinates look like lon/lat:
                - lon in [-180, 360]
                - lat in [-90, 90]
                """
                xs = []
                ys = []

                def collect_coords(geom_json):
                    gtype = geom_json.get("type")
                    coords = geom_json.get("coordinates", [])

                    if gtype == "LineString":
                        for pt in coords:
                            if len(pt) >= 2:
                                xs.append(pt[0])
                                ys.append(pt[1])
                                if len(xs) >= max_points:
                                    return True
                    elif gtype == "MultiLineString":
                        for line in coords:
                            for pt in line:
                                if len(pt) >= 2:
                                    xs.append(pt[0])
                                    ys.append(pt[1])
                                    if len(xs) >= max_points:
                                        return True
                    return False

                # Sample up to max_features features and up to max_points points
                for c in islice(contour_wrappers, max_features):
                    f = c["feature"]
                    geom_json = json.loads(f.geometry().asJson())
                    if collect_coords(geom_json):
                        break

                if not xs:
                    # No coordinates to inspect → treat as "doesn't look good"
                    return False

                min_x = min(xs)
                max_x = max(xs)
                min_y = min(ys)
                max_y = max(ys)

                # Allow lon in [-180, 360] (some datasets use 0–360)
                if min_x < -180.0 or max_x > 360.0:
                    return False

                # Lat must be in [-90, 90]
                if min_y < -90.0 or max_y > 90.0:
                    return False

                return True

            if not coords_look_lonlat(contours):
                QMessageBox.critical(
                    None,
                    "Invalid contour coordinates",
                    (
                        "The contour layer has no CRS defined and the coordinates "
                        "do not look like longitude/latitude.\n\n"
                        f"Layer CRS: {crs.authid() or 'undefined'} - {crs.description()}\n\n"
                        "Contours should be in a geographic CRS (e.g. EPSG:4326) with:\n"
                        "  - longitude in roughly [-180, 360]\n"
                        "  - latitude in [-90, 90]\n\n"
                        "Please define or reproject your contours to EPSG:4326 in QGIS and try again."
                    ),
                )
                return

        # Extract features for validation
        features = [c['feature'] for c in contours]

        # Validate the selected contours
        errors = get_invalid_contour_messages(features)
        if errors:
            error_msg = "The following contour features are invalid:\n" + "\n".join(errors)
            QMessageBox.critical(None, "Invalid Contours", error_msg)
            return  # Cancel processing

        name, spacing, out_path, elevation_path = dlg.get_values()

        # Handle temporary file output
        if dlg.is_using_temp_file():
            # Create a temporary file
            temp_file = tempfile.NamedTemporaryFile(suffix='.geojson', delete=False)
            out_path = temp_file.name
            temp_file.close()

        print("Contours2Surface Parameters:")
        print(f"  name: {name}")
        print(f"  spacing: {spacing}")
        print(f"  output path: {out_path}")
        print(f"  elevation path: {elevation_path if elevation_path else 'None'}")
        print(f"  using temp file: {dlg.is_using_temp_file()}")

        # --- Ensure all contours have a valid numeric elevation ---

        invalid_elev_ids = []
        for c in contours:
            f = c["feature"]
            if _feature_geometry_has_z(f):
                continue
            try:
                z = _qvariant_to_float(f["elev"], return_none=True)
            except Exception:
                z = None

            if z is None:
                invalid_elev_ids.append(str(f.id()))

        if invalid_elev_ids:
            QMessageBox.critical(
                None,
                "Missing elevations",
                (
                    "All selected contours must have a valid numeric 'elev' attribute.\n\n"
                    "The following feature IDs are missing or have invalid 'elev' values:\n"
                    f"{', '.join(invalid_elev_ids)}\n\n"
                    "Please set the 'elev' field for these contours in QGIS and try again."
                ),
            )
            return

        def feature_to_geojson(f):
            fields = [field.name() for field in f.fields()]
            props_dict = {field: f[field] for field in fields}

            geom = f.geometry()
            if "elev" in fields:
                props_dict["elev"] = _qvariant_to_float(f["elev"], return_none=True)
            else:
                props_dict["elev"] = None

            # asJson() strips Z; build coordinates manually when the geometry has Z
            # so per-vertex elevations reach prepare_fault_contours.
            if QgsWkbTypes.hasZ(geom.wkbType()):
                flat_type = QgsWkbTypes.flatType(geom.wkbType())
                if flat_type == QgsWkbTypes.LineString:
                    coords = [[v.x(), v.y(), v.z()] for v in geom.vertices()]
                    geom_json = {"type": "LineString", "coordinates": coords}
                else:  # MultiLineString
                    parts = []
                    for part in geom.constGet():
                        parts.append([[p.x(), p.y(), p.z()] for p in part.vertices()])
                    geom_json = {"type": "MultiLineString", "coordinates": parts}
            else:
                geom_json = json.loads(geom.asJson())

            return {
                "type": "Feature",
                "geometry": geom_json,
                "properties": props_dict
            }

        geojson_features = [feature_to_geojson(c['feature']) for c in contours]
        try:
            prepped = prepare_fault_contours(geojson_features, pt_distance=spacing, elevation_path=elevation_path)
            # Estimate mesh complexity before meshing
            estimated_triangles = estimate_triangle_count(prepped, spacing)
            print(f"Estimated triangle count: {estimated_triangles}")
            MAX_TRIANGLES = 50_000

            if estimated_triangles > MAX_TRIANGLES:
                QMessageBox.critical(None, "Mesh too large",
                                     f"Mesh would generate approximately {estimated_triangles:,} triangles, "
                                     f"which exceeds the safe limit of {MAX_TRIANGLES:,}.\n"
                                     f"Please increase spacing to reduce complexity.")
                return

            # Mesh generation
            mesh = make_mesh_from_prepared_contours(prepped, down_dip_pt_spacing=spacing)
            tri_mesh = make_tri_mesh(mesh)

            write_cfm_tri_meshes(out_path, [tri_mesh], [{'properties': {'name': name}}])

            result_layer = QgsVectorLayer(out_path, name, "ogr")
            if result_layer.isValid():
                QgsProject.instance().addMapLayer(result_layer)
                QMessageBox.information(None, "Success", f"Mesh '{name}' generated successfully!")
            else:
                raise RuntimeError("Generated mesh layer could not be loaded.")


        except Exception as e:

            import traceback

            tb = traceback.format_exc()

            print(tb)  # goes to QGIS Python console

            # Or also log to the QGIS log panel:

            from qgis.core import QgsMessageLog, Qgis

            QgsMessageLog.logMessage(tb, "Contours2Surface", Qgis.Critical)

            QMessageBox.critical(None, "Contours2Surface Error", f"{e}\n\n{tb}")
