# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Contours2SurfacePlugin
                                 A QGIS plugin
 Generate 3D fault surfaces or geological meshes from top, middle, and bottom contour lines in QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by CRESCENT
        email                : lbachelo@uoregon.edu
***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify *
 *   it under the terms of the GNU General Public License as published by *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QFileDialog, QInputDialog
from qgis.core import QgsProject, QgsVectorLayer, QgsWkbTypes
import os, tempfile, json

from .ccfm.ccfm import make_tri_mesh, write_cfm_tri_meshes
from .ccfm.mesh_helpers import prepare_fault_contours, make_mesh_from_prepared_contours, get_invalid_contour_messages, estimate_triangle_count
from .input_dialog import MeshInputDialog


class Contours2SurfacePlugin:
    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', f'Contours2SurfacePlugin_{locale}.qm')
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
        self.actions = []
        self.menu = self.tr('&Contours2Surface')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('Contours2SurfacePlugin', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True,
                   add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, "icon.png")
        self.add_action(
            icon_path,
            text=self.tr('Generate 3D Surface from Contours'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        selected_layers = self.iface.layerTreeView().selectedLayers()

        if len(selected_layers) != 1:
            QMessageBox.warning(None, "Contours2Surface", "Please select one layer containing at least 2 contour features.")
            return

        layer = selected_layers[0]
        features = [f for f in layer.getFeatures()]

        # Check geometry type of each feature
        for f in features:
            geom = f.geometry()
            geom_type = QgsWkbTypes.flatType(geom.wkbType())
            if geom_type != QgsWkbTypes.LineString:
                QMessageBox.critical(None, "Contours2Surface",
                                     f"Invalid geometry type: {QgsWkbTypes.displayString(geom.wkbType())}. "
                                     f"All features must be simple LineStrings.")
                return

        errors = get_invalid_contour_messages(features)

        if errors:
            error_msg = "The following contour features are invalid:\n" + "\n".join(errors)
            QMessageBox.critical(None, "Invalid Contours", error_msg)
            return  # Cancel processing

        if len(features) < 2:
            QMessageBox.critical(None, "Contours2Surface", "Selected layer must contain at least 2 contours.")
            return

        try:
            # Extract features with their elevation
            features_with_elev = [(f, f["elev"]) for f in features]
        except KeyError:
            QMessageBox.critical(None, "Contours2Surface", "All features must have an 'elev' field.")
            return

        contours = []
        for f in features:
            name = f["name"] if "name" in f.fields().names() else "Unnamed"
            depth = f["elev"] if "elev" in f.fields().names() else 0
            contours.append({'name': name, 'depth': depth, 'feature': f})

        # Show the mesh input dialog
        dlg = MeshInputDialog(contours)
        if not dlg.exec_():
            return  # user cancelled

        name, spacing, out_path, elevation_path = dlg.get_values()
        print("Contours2Surface Parameters:")
        print(f"  name: {name}")
        print(f"  spacing: {spacing}")
        print(f"  output path: {out_path}")
        print(f"  elevation path: {elevation_path if elevation_path else 'None'}")
        if not name.strip() or not out_path.strip():
            QMessageBox.warning(None, "Contours2Surface", "Please fill in all required fields.")
            return

        def feature_to_geojson(f):
            props = f.attributes()
            fields = [field.name() for field in f.fields()]
            props_dict = {field: f[field] for field in fields}

            # Ensure 'elev' is explicitly included
            props_dict["elev"] = f["elev"]

            return {
                "type": "Feature",
                "geometry": json.loads(f.geometry().asJson()),
                "properties": props_dict
            }

        geojson_features = [feature_to_geojson(f) for f in dlg.get_selected_contours()]
        try:
            prepped = prepare_fault_contours(geojson_features, pt_distance=spacing, elevation_path=elevation_path)
            # Estimate mesh complexity before meshing
            estimated_triangles = estimate_triangle_count(prepped, spacing)
            print(f"Estimated triangle count: {estimated_triangles}")
            MAX_TRIANGLES = 50_000

            if estimated_triangles > MAX_TRIANGLES:
                QMessageBox.critical(None, "Mesh too large",
                                     f"Mesh would generate approximately {estimated_triangles:,} triangles, "
                                     f"which exceeds the safe limit of {MAX_TRIANGLES:,}.\n"
                                     f"Please increase spacing to reduce complexity.")
                return

            # Mesh generation
            mesh = make_mesh_from_prepared_contours(prepped, down_dip_pt_spacing=spacing)
            tri_mesh = make_tri_mesh(mesh)

            write_cfm_tri_meshes(out_path, [tri_mesh], [{'properties': {'name': name}}])

            result_layer = QgsVectorLayer(out_path, name, "ogr")
            if result_layer.isValid():
                QgsProject.instance().addMapLayer(result_layer)
            else:
                raise RuntimeError("Generated mesh layer could not be loaded.")

        except Exception as e:
            QMessageBox.critical(None, "Contours2Surface Error", str(e))
